import docx
from docx.shared import Inches, Pt
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

doc = docx.Document()
doc.add_heading('CHƯƠNG 2: CƠ SỞ LÝ THUYẾT', level=1)

sections = [
    (
        '2.1. Ngôn ngữ lập trình C# (C Sharp)',
        'C# (đọc là C Sharp) là một ngôn ngữ lập trình hướng đối tượng, đa mục đích và vô cùng mạnh mẽ do Microsoft phát triển. Ra đời vào đầu những năm 2000 như một phần cốt lõi của nền tảng .NET, C# được thiết kế với mục tiêu kết hợp sức mạnh tính toán của C++ với sự đơn giản, dễ học của Visual Basic. Trong suốt hơn hai thập kỷ qua, C# liên tục được cập nhật và phát triển, trở thành một trong những ngôn ngữ phổ biến nhất trên thế giới, đặc biệt là trong việc phát triển các ứng dụng doanh nghiệp, ứng dụng web, phần mềm máy bàn và trò chơi điện tử.\n\nĐặc điểm nổi bật của C# là tính định kiểu mạnh (strongly-typed), khả năng thu gom rác tự động (Garbage Collection) giúp quản lý bộ nhớ hiệu quả, và hỗ trợ mạnh mẽ các nguyên lý của lập trình hướng đối tượng (OOP) như tính đóng gói, tính kế thừa, tính đa hình và tính trừu tượng. Bên cạnh đó, C# cung cấp một loạt các tính năng hiện đại như LINQ (Language Integrated Query), lập trình bất đồng bộ (Async/Await) và Lambda Expressions, giúp các lập trình viên có thể viết mã một cách ngắn gọn, tối ưu và an toàn.\n\nTrong khuôn khổ dự án PandoraWeb, C# đóng vai trò là ngôn ngữ lập trình chủ đạo ở phía Server (Backend). Ngôn ngữ này được sử dụng để xây dựng các Controller (bộ điều khiển) xử lý các luồng nghiệp vụ phức tạp như: quy trình đăng nhập, đăng ký tài khoản, xử lý thuật toán thêm sản phẩm vào giỏ hàng, tính toán tổng tiền và quản lý các hóa đơn đặt hàng. Nhờ cấu trúc rõ ràng và hệ sinh thái thư viện phong phú từ NuGet, C# giúp dự án dễ dàng tích hợp các công nghệ khác, đồng thời đảm bảo hệ thống hoạt động ổn định và có khả năng mở rộng bảo trì trong tương lai.'
    ),
    (
        '2.2. Mô hình kiến trúc ASP.NET MVC 5',
        'ASP.NET MVC 5 là một nền tảng phát triển ứng dụng web hiện đại và tối ưu của Microsoft, được xây dựng dựa trên nguyên lý kiến trúc MVC (Model - View - Controller). Kiến trúc MVC là một mẫu thiết kế phần mềm kinh điển, giúp phân tách rõ ràng hệ thống thành ba thành phần độc lập, qua đó giải quyết triệt để sự lộn xộn trong mã nguồn thường gặp ở các ứng dụng web truyền thống (như Web Forms).\n\nCấu trúc ba thành phần cốt lõi bao gồm:\n- Model (Mô hình): Là thành phần chịu trách nhiệm quản lý cấu trúc dữ liệu, trạng thái và các quy tắc nghiệp vụ logic của ứng dụng. Model thường tương tác trực tiếp với cơ sở dữ liệu để thực hiện các thao tác thêm, sửa, xóa và truy xuất dữ liệu.\n- View (Giao diện): Là thành phần phụ trách việc hiển thị dữ liệu tới người dùng cuối. Trong ASP.NET MVC, View sử dụng Razor Engine (với cú pháp .cshtml) cho phép nhúng trực tiếp mã C# vào bên trong các thẻ HTML, tạo ra các giao diện web động vô cùng linh hoạt.\n- Controller (Bộ điều khiển): Đóng vai trò là cầu nối trung tâm giữa Model và View. Khi nhận được một yêu cầu (HTTP Request) từ trình duyệt, Controller sẽ phân tích yêu cầu đó, gọi Model tương ứng để lấy hoặc cập nhật dữ liệu, sau đó truyền dữ liệu này sang một View thích hợp để kết xuất ra HTML trả về cho người dùng.\n\nViệc áp dụng ASP.NET MVC 5 cho dự án PandoraWeb mang lại nhiều lợi ích to lớn. Đầu tiên, nó giúp các thành viên trong nhóm có thể làm việc song song: người thiết kế giao diện có thể làm việc trên View trong khi lập trình viên Backend có thể xây dựng Controller và Model mà không gây xung đột. Thứ hai, cơ chế Routing (Định tuyến) linh hoạt của MVC giúp tạo ra các đường dẫn (URL) thân thiện với người dùng và tối ưu cho công cụ tìm kiếm (SEO). Cuối cùng, việc kiểm thử tự động (Unit Testing) trở nên dễ dàng hơn bao giờ hết nhờ sự tách biệt hoàn toàn giữa giao diện và logic xử lý.'
    ),
    (
        '2.3. Hệ quản trị CSDL Microsoft SQL Server',
        'Microsoft SQL Server là một hệ quản trị cơ sở dữ liệu quan hệ (RDBMS) cấp doanh nghiệp, được phát triển và hỗ trợ bởi tập đoàn Microsoft. Kể từ khi ra mắt, SQL Server đã khẳng định được vị thế vững chắc của mình trong ngành công nghệ thông tin nhờ khả năng lưu trữ dữ liệu an toàn, xử lý truy vấn với tốc độ cao và khả năng mở rộng linh hoạt đáp ứng từ các ứng dụng nhỏ lẻ đến các hệ thống quy mô tập đoàn.\n\nNgôn ngữ truy vấn chính được sử dụng trong SQL Server là T-SQL (Transact-SQL), một phiên bản mở rộng của chuẩn SQL do Microsoft phát triển, cung cấp thêm các cấu trúc lập trình như biến, vòng lặp, xử lý ngoại lệ (Try/Catch) và các hàm hệ thống chuyên dụng. SQL Server nổi bật với cơ chế đảm bảo tính toàn vẹn dữ liệu cực kỳ khắt khe theo tiêu chuẩn ACID (Atomicity, Consistency, Isolation, Durability). Điều này đồng nghĩa với việc mọi giao dịch (Transaction) liên quan đến dữ liệu đều được thực thi một cách trọn vẹn; nếu xảy ra bất kỳ lỗi nhỏ nào trong quá trình xử lý, toàn bộ giao dịch sẽ được hoàn tác (Rollback) để trả dữ liệu về trạng thái an toàn ban đầu.\n\nTrong bài toán xây dựng website thương mại điện tử PandoraWeb, dữ liệu đóng vai trò là mạch máu của toàn bộ hệ thống. Microsoft SQL Server được lựa chọn làm giải pháp lưu trữ tập trung cho toàn bộ thông tin của website. Nó chịu trách nhiệm lưu giữ một cách bảo mật các thông tin nhạy cảm của khách hàng, quản lý danh mục sản phẩm phức tạp với hàng ngàn thuộc tính, lưu trữ lịch sử giao dịch và theo dõi trạng thái đơn hàng. Thông qua hệ thống các khóa chính (Primary Key) và khóa ngoại (Foreign Key), SQL Server đảm bảo tính nhất quán và toàn vẹn tham chiếu của các bảng dữ liệu, ngăn chặn tình trạng dữ liệu mồ côi hoặc sai lệch trong quá trình vận hành lâu dài.'
    ),
    (
        '2.4. Entity Framework 6 (EF6) và LINQ',
        'Entity Framework 6 (EF6) là một framework Object-Relational Mapping (ORM) mã nguồn mở, mạnh mẽ dành cho các ứng dụng .NET. Hiểu một cách đơn giản, ORM là công nghệ đóng vai trò như một thông dịch viên, kết nối giữa thế giới lập trình hướng đối tượng (với các Class, Object trong C#) và thế giới cơ sở dữ liệu quan hệ (với các Table, Column, Row trong SQL Server). Thay vì phải viết hàng ngàn dòng lệnh SQL thuần túy phức tạp và dễ mắc lỗi để thao tác với cơ sở dữ liệu, EF6 cho phép các lập trình viên thực hiện điều này thông qua mã C# trực quan.\n\nDự án áp dụng phương pháp tiếp cận Code-First của EF6. Nghĩa là, hệ thống cơ sở dữ liệu sẽ được sinh ra tự động dựa trên các lớp mô hình (Model Classes) được định nghĩa bằng C#. Khi cấu trúc dữ liệu thay đổi, lập trình viên chỉ cần sử dụng cơ chế Migrations để cập nhật cấu trúc bảng trong SQL Server mà không làm mất mát dữ liệu hiện có. Điều này giúp đẩy nhanh đáng kể tốc độ phát triển và giảm thiểu tối đa các lỗi do bất đồng bộ giữa mã nguồn và cơ sở dữ liệu.\n\nĐồng hành cùng EF6 là công nghệ LINQ (Language Integrated Query) – Ngôn ngữ truy vấn tích hợp. LINQ là một bước đột phá của C#, mang cú pháp truy vấn tương tự như SQL vào trực tiếp trong ngôn ngữ lập trình. Việc kết hợp EF6 và LINQ (LINQ to Entities) cho phép các truy vấn C# được biên dịch ngầm thành các câu lệnh SQL tối ưu trước khi gửi đến máy chủ CSDL. Điểm sáng giá nhất của sự kết hợp này là khả năng ngăn chặn hoàn toàn lỗ hổng bảo mật khét tiếng SQL Injection, bởi mọi dữ liệu đầu vào đều được tự động tham số hóa (Parameterized) một cách nghiêm ngặt.'
    ),
    (
        '2.5. Dịch vụ lưu trữ tài nguyên đám mây Cloudinary',
        'Cloudinary là một nền tảng quản lý tài nguyên truyền thông dựa trên điện toán đám mây (Cloud-based Media Management Platform) cung cấp giải pháp toàn diện cho việc lưu trữ, tối ưu hóa và phân phối hình ảnh cũng như video trực tuyến. Trong kỷ nguyên web hiện đại, khi mà hình ảnh chất lượng cao chiếm phần lớn dung lượng của một trang web, việc xử lý và tải hình ảnh hiệu quả là yếu tố then chốt quyết định trải nghiệm người dùng.\n\nThay vì lưu trữ hình ảnh vật lý trực tiếp trên máy chủ web nội bộ – một phương pháp truyền thống gây tốn kém không gian ổ cứng, làm chậm tốc độ phản hồi của máy chủ và khó sao lưu, dự án PandoraWeb đã tích hợp Cloudinary API để giải quyết triệt để vấn đề này. Khi người quản trị viên tải lên một hình ảnh sản phẩm mới, hình ảnh đó lập tức được đẩy lên máy chủ bảo mật của Cloudinary. Tại đây, Cloudinary sẽ tự động thực hiện các thuật toán nén thông minh (Smart Compression), giảm dung lượng file xuống mức thấp nhất nhưng vẫn giữ nguyên độ sắc nét của hình ảnh gốc.\n\nHơn thế nữa, Cloudinary hỗ trợ thao tác xử lý ảnh động ngay trên đường dẫn URL (on-the-fly transformations), cho phép tự động cắt cúp (crop), căn chỉnh kích thước (resize) hình ảnh cho phù hợp với từng thiết bị hiển thị mà không cần tạo ra nhiều bản sao khác nhau. Cuối cùng, mọi hình ảnh được phân phối đến trình duyệt của khách hàng thông qua mạng lưới phân phối nội dung toàn cầu CDN (Content Delivery Network). Điều này đảm bảo rằng dù khách hàng truy cập website PandoraWeb từ bất kỳ vị trí địa lý nào, hình ảnh sản phẩm cũng sẽ được tải xuống với tốc độ nhanh nhất từ máy chủ gần họ nhất, mang lại trải nghiệm mua sắm mượt mà không độ trễ.'
    ),
    (
        '2.6. Công nghệ Front-End (HTML5, CSS3, Bootstrap 5)',
        'Giao diện người dùng (Front-End) là cầu nối giao tiếp trực tiếp giữa khách hàng và hệ thống website. Một giao diện đẹp, trực quan và phản hồi nhanh chóng là yếu tố quyết định để giữ chân khách hàng ở lại với trang thương mại điện tử. Hệ thống PandoraWeb sử dụng một bộ ba công nghệ Front-End tiêu chuẩn và mạnh mẽ nhất hiện nay: HTML5, CSS3 và Bootstrap 5.\n\nHTML5 (HyperText Markup Language phiên bản 5) là nền tảng cốt lõi định hình cấu trúc của toàn bộ trang web. HTML5 mang đến các thẻ ngữ nghĩa (Semantic Tags) rõ ràng như <header>, <footer>, <nav>, <article>, giúp mã nguồn trở nên mạch lạc, dễ đọc và hỗ trợ tối đa cho các công cụ tìm kiếm (SEO) khi lập chỉ mục nội dung trang. Kế tiếp đó, CSS3 (Cascading Style Sheets) đóng vai trò như chiếc áo khoác thẩm mỹ cho website. Với CSS3, dự án đã triển khai các hiệu ứng thiết kế hiện đại như đổ bóng, bo góc, chuyển động mượt mà (transitions và animations) và đặc biệt là áp dụng phong cách thiết kế kính mờ (Glassmorphism), mang lại cho PandoraWeb một diện mạo sang trọng, cao cấp và chuyên nghiệp.\n\nTuy nhiên, để đảm bảo giao diện hiển thị hoàn hảo trên vô số các thiết bị khác nhau từ máy tính để bàn, laptop cho đến điện thoại di động, dự án đã sử dụng Bootstrap 5. Bootstrap là một framework CSS mã nguồn mở phổ biến nhất thế giới, cung cấp sẵn một hệ thống lưới 12 cột linh hoạt (Grid System) dựa trên nền tảng Flexbox. Thay vì phải viết hàng ngàn dòng code CSS phức tạp để tinh chỉnh bố cục cho từng kích thước màn hình, việc sử dụng các class có sẵn của Bootstrap 5 giúp giao diện PandoraWeb tự động co giãn, thích ứng hoàn hảo với mọi thiết bị (Responsive Web Design). Bên cạnh đó, các thành phần UI đúc sẵn như thanh điều hướng (Navbar), các hộp thoại bật lên (Modal), băng chuyền hình ảnh (Carousel) đã giúp tiết kiệm đáng kể thời gian phát triển giao diện.'
    ),
    (
        '2.7. Thư viện xử lý JavaScript (jQuery & Newtonsoft.Json)',
        'Bên cạnh giao diện tĩnh, tính tương tác và tính động của website là yếu tố cực kỳ quan trọng để mang lại trải nghiệm chân thực như một ứng dụng phần mềm thực thụ. Để làm được điều này mà không cần phải tải lại trang nhiều lần (gây khó chịu cho người dùng), dự án đã ứng dụng thư viện jQuery và các kỹ thuật xử lý dữ liệu JSON mạnh mẽ.\n\njQuery là một thư viện JavaScript nhẹ, nhanh chóng và giàu tính năng, ra đời với tiêu chí "Write less, do more" (Viết ít hơn, làm nhiều hơn). Mặc dù các framework JavaScript hiện đại đang nổi lên, jQuery vẫn giữ vai trò quan trọng trong việc đơn giản hóa các thao tác tương tác với mô hình DOM (Document Object Model). Trong PandoraWeb, jQuery được sử dụng rộng rãi để xử lý các sự kiện click chuột, tạo các hiệu ứng ẩn hiện mượt mà và đặc biệt là thực hiện các kỹ thuật Client-side Validation (Kiểm tra tính hợp lệ dữ liệu ở phía máy khách). Nhờ jQuery Validation, ngay khi người dùng nhập sai định dạng email hoặc bỏ trống trường mật khẩu, hệ thống lập tức hiển thị thông báo lỗi màu đỏ mà không cần phải gửi dữ liệu lên máy chủ, giúp tiết kiệm băng thông và phản hồi tức thì cho người dùng.\n\nBên cạnh đó, trong các tác vụ gọi dữ liệu ngầm (AJAX) như thêm sản phẩm vào giỏ hàng hoặc cập nhật số lượng, dữ liệu trao đổi giữa trình duyệt và máy chủ cần được đóng gói dưới định dạng chuẩn. Newtonsoft.Json (hay còn gọi là Json.NET) là một thư viện tiêu chuẩn trong hệ sinh thái .NET đảm nhiệm vai trò này. Nó cung cấp khả năng tuần tự hóa (Serialize) các đối tượng C# phức tạp thành chuỗi văn bản JSON nhẹ gọn để gửi về trình duyệt, và ngược lại, giải mã (Deserialize) dữ liệu JSON từ Client gửi lên thành các đối tượng C# tương ứng. Quá trình chuyển đổi này diễn ra với hiệu suất cực cao và độ chính xác tuyệt đối, đảm bảo luồng giao tiếp mượt mà giữa Front-End và Back-End của PandoraWeb.'
    )
]

for title, content in sections:
    doc.add_heading(title, level=2)
    p_img = doc.add_paragraph()
    p_img.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run_img = p_img.add_run('[HÌNH ẢNH LOGO CÔNG NGHỆ BẠN CHÈN VÀO ĐÂY (Canh giữa)]')
    run_img.italic = True
    run_img.bold = True
    
    # Split content by paragraphs
    for para_text in content.split('\n\n'):
        p = doc.add_paragraph(para_text)
        p.alignment = WD_PARAGRAPH_ALIGNMENT.JUSTIFY
        
# Configure style (font Times New Roman, size 13 is typical for thesis)
for p in doc.paragraphs:
    for run in p.runs:
        run.font.name = 'Times New Roman'
        run.font.size = Pt(13)
        
output_path = r'c:\Users\thean\Desktop\PandoraWeb\FILEBAOCAO\Chuong2_DaSua_ChiTiet.docx'
doc.save(output_path)
print(f'Saved to {output_path}')
